### ISSUE TITLE
请问有炽焰苍穹的CG解包吗，截图放大还是模糊想要解包原图，如果有音频就更好了

### ISSUE THREAD

**Issue by yuanxingyechangming** [cc004/HBRToolkits#3]
请问有炽焰苍穹的CG解包吗，截图放大还是模糊想要解包原图，如果有音频就更好了

**Comment by cc004** [comment]
用[AssetStudio](https://github.com/Perfare/AssetStudio)解`Android\data\com.bilibili.heaven\files\UnityCache\Shared`

**Comment by yuanxingyechangming** [comment]
我之前就试过了，用mumu模拟器的包解出来没有用（按照路径从模拟器里导出的），包是没有后缀的，请问这样的情况是必须用手机上的包还是需要把所有文件一起放入或将Shared整个文件夹放入AssetStudio才行，整个Shared太大了

**Comment by cc004** [comment]
> 我之前就试过了，用mumu模拟器的包解出来没有用（按照路径从模拟器里导出的），包是没有后缀的，请问这样的情况是必须用手机上的包还是需要把所有文件一起放入或将Shared整个文件夹放入AssetStudio才行，整个Shared太大了

我刚才试了是没有问题的 后缀是无所谓的，可以单个解

**Comment by yuanxingyechangming** [comment]
刚又试了一下，才发现之前解包解错目录了，现在成功了，不过文件都是乱码无序的，上千个文件从中找出想要的CG还有什么方法吗，只能一个个解吗，如果没有的话就不再麻烦您了

**Comment by cc004** [comment]
> 刚又试了一下，才发现之前解包解错目录了，现在成功了，不过文件都是乱码无序的，上千个文件从中找出想要的CG还有什么方法吗，只能一个个解吗，如果没有的话就不再麻烦您了

repo里面的[HBRAssetManager](https://github.com/cc004/HBRMasterDecrypt/tree/main/HBRAssetManager)可以生成依赖列表，但是需要手动做下载，我更建议用AssetRipper全部解出来
